#!/bin/sh
# See http://www.wtfpl.net/txt/copying for license details
# Creates a minimal manifest and manifest.uuid file so sqlite (and fossil) can build
git rev-parse --git-dir >/dev/null || exit 1
TZ=UTC date -r $(git log -1 --format=format:%ct) '+D %Y-%m-%dT%H:%M:%S' > manifest
echo $(git log -1 --format=format:%H) > manifest.uuid
